services:
  - type: web
    name: vinyl-wrapper-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.10.0
